Layout/LineLength:
  Max: 120

Metrics/MethodLength: 
  Max: 20

Metrics/ClassLength:
  Max: 1500

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 30
